# Generated by Django 2.2.6 on 2020-08-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounddb', '0003_auto_20200610_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
