#!/usr/bin/python
# -*- coding: utf-8 -*-

"""calculate total time, using timestampe file generated by `date'. 
Each file contains two lines, one for start time, and one for end time
"""

import sys


def seconds(t):
    (h, m, s) = [int(i) for i in t.split(':')]
    return h * 3600 + m * 60 + s


total_time = 0
for f in sys.argv[1:]:
    (s, e) = [i.split()[3] for i in file(f).readlines()]
    elapse = seconds(e) - seconds(s)
    if elapse < 0:
        elapse += 3600 * 24
    total_time += elapse

print total_time
